replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "tekton-github-interceptor"
fullnameOverride: "tekton-github-interceptor"

service:
  type: ClusterIP
  port: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
