apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-push-run-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting ci/resources"
spec:
  serviceAccount: docker
  pipelineRef:
    name: build-push-dockerfile
  resources:
    - name: source-repo
      resourceSpec:
        type: git
        params:
        - name: revision
          value: {{ .Values.global.ci.repository.revision }}
        - name: url
          value: {{ .Values.global.ci.repository.url }}
    - name: docker-image
      resourceSpec:
        type: image
        params:
          - name: url
            value: {{ .Values.image.name }}
