apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-push-deploy-dockerfile
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
spec:
  resources:
    - name: source-repo
      type: git
    - name: docker-image
      type: image
  params:
    - name: helmPath
      type: string
      description: Path of the app helm chart relative to the source repo root
  tasks:
    - name: build-image
      taskRef:
        name: build-push-kaniko
      params:
        - name: pathToContext
          value: /workspace/source
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: image
            resource: docker-image
    - name: deploy
      taskRef:
        name: deploy-helm
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: docker-image
            from:
              - build-image
      params:
        - name: helmPath
          value: $(params.helmPath)
