apiVersion: v1
kind: Secret
metadata:
  name: docker
  annotations:
    tekton.dev/docker-0: {{ .Values.secrets.docker.url }}
    kapp.k14s.io/change-group: "ci/resources"
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.global.ci.secrets.docker.username }}
  password: {{ .Values.global.ci.secrets.docker.password }}
