apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-helm
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: helmPath
        type: string
        description: Path to the chart to apply
  steps:
    - name: get-ci-context
      image: nixery.dev/shell/kubectl
      command: ["bash"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - -ce
        - |
          kubectl get configmap ci-context-{{ .Values.global.ci.uid }} -o=jsonpath="{.data.context}" > values-global.yaml
          cat values-global.yaml
    - name: gen-image-value
      image: nixery.dev/shell/yq
      command: ["bash"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - -ce
        - |
          echo "{global: {ci: {image: {url: $(inputs.resources.image.url)}}}}" | yq -y . > values-global-image.yaml
          cat values-global-image.yaml
    - name: helm-template
      image: nixery.dev/shell/kubernetes-helm
      command: ["bash"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - -ce
        - |
          helm template . --values=values-global-image.yaml --values=values-global.yaml > rendered.yaml
    - name: kapp-deploy
      image: eonpatapon/kapp
      command: ["kapp"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - deploy
        - -a
        - {{ .Values.global.ci.repository.name }}
        - -n
        - {{ .Values.global.ci.namespace }}
        - -f
        - rendered.yaml
        - -y
