apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-helm
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
    kapp.k14s.io/disable-associated-resources-wait: ""
  namespace: {{ .Values.namespace }}
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: helmPath
        type: string
        description: Path to the chart to apply
  steps:
    - name: gen-image-value
      image: nixery.dev/shell/yq
      command: ["bash"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - -ce
        - |
          echo "{image: {url: $(inputs.resources.image.url), digest: $(inputs.resources.image.digest)}}" | yq -y . > values-image.yaml
          cat values-image.yaml
    - name: helm-template
      image: nixery.dev/shell/kubernetes-helm/yq
      command: ["bash"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - -ce
        - |
          echo '{"global": {"ci": {"eventType": "{{ .Values.global.ci.eventType}}", "secrets": {"github": {"token": "{{.Values.global.ci.secrets.github.token }}" }}}}}' | yq . -y > values-global.yaml
          cat values-global.yaml
          helm template . --values=values-image.yaml --values=values-global.yaml > rendered.yaml
          cat rendered.yaml
    - name: kapp-deploy
      image: eonpatapon/kapp
      command: ["kapp"]
      workingDir: /workspace/source/$(inputs.params.helmPath)
      args:
        - deploy
        - -a
        - {{ .Values.global.ci.repository.name }}
        - -n
        - {{ .Values.namespace }}
        - -f
        - rendered.yaml
        - -y
